#pragma once
#define LABEL_ASYNC_ERR			"Async Query Error"
#define LABEL_INPUT_ERR			"Input error"
#define MSG_INPUT_ERR_NOINPUT	"No input"
#define MSG_WSAENETDOWN			"The network subsystem has failed."
#define MSG_WSAENOBUFS			"Insufficient buffer space is available."
#define MSG_WSAEFAULT			"The proto or buf parameter is not in a valid part of the process address space."
#define MSG_WSAHOST_NOT_FOUND	"Authoritative answer port not found."
#define MSG_WSATRY_AGAIN		"Nonauthoritative port not found, or server failure."
#define MSG_WSANO_RECOVERY		"Nonrecoverable errors, the services database is not accessible."
#define MSG_WSANO_DATA			"Valid name, no data record of requested type."
#define MSG_WSANOTINITIALISED   "A successful WSAStartup must occur before using this function."
#define MSG_WSAEINPROGRESS		"A blocking Windows Sockets 1.1 call is in progress, or the service provider is still processing a callback function."
#define MSG_WSAEWOULDBLOCK		"The asynchronous operation cannot be scheduled at this time due to resource or other constraints within the Windows Sockets implementation."
